version: '3.7'

networks:
    default:
    elastic:
        driver: bridge

services:
    viam_fpm: &container
        build:
            context: ./local
            dockerfile: Dockerfile_fpm
        container_name: viam_fpm
        restart: always
        networks:
            - default
        volumes:
            - &data-app ../:/app
            - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini
            - ./local/config/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        depends_on:
            - viam_postgres

    viam_nginx:
        build:
            context: ./local
            dockerfile: Dockerfile_nginx
        container_name: viam_nginx
        ports:
            - 8080:80
        restart: always
        volumes:
            - *data-app
            - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./local/config/nginx/site.conf:/etc/nginx/site.conf
        networks:
            - default
        depends_on:
            - viam_fpm

    viam_postgres:
        image: library/postgres:14.5-bullseye
        networks:
            - default
        restart: always
        container_name: viam_db
        environment:
          POSTGRES_USER: viam
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: viam_db
        ports:
          - "5432:5432"

